### ISSUE TITLE
关于RDMA通信的实现有些问题想咨询一下

### ISSUE THREAD

**Issue by hellofinch** [Tuvie/brpc#2]
您在brpc项目中对于RDMA的支持为brpc在高性能通信网络中rpc框架的高效使用提供了可能，对于采用RPC框架的分布式程序在IB网络上的性能潜力提供了更大的希望。同时在brpc中的issue中对于RDMA相关内容的解决也能感受到您在RDMA方面进行的透彻的研究。

目前我在针对gRPC框架添加相关的RDMA支持，以提高gRPC框架在高性能通信网络上的通信性能表现。但是，在实现过程中出现了一些问题。
对于非流式的通信方式下，server端和client端可以通过RDMA进行数据报文的通信。但是在流式通信时，会出现一些非流式通信中没有出现过的问题。

我目前接触RDMA技术不久，可能在设计和实现过程中有遗漏的地方，希望和您交流一下您在brpc中对RDMA提供支持时是如何设计整个通信过程的。

**Comment by Tuvie** [comment]
> 但是在流式通信时，会出现一些非流式通信中没有出现过的问题。

具体是指哪方面问题呢

**Comment by hellofinch** [comment]
非常感谢您能抽时间耐心看完我的问题。

我使用流式传输的目的是为了实现对于文件这种比较大的数据的传输。在这个前提下，一次通信不能把数据都发完，需要多次发送。我在服务器端把接收到的数据能够打印出来，但是不是我发送的完整数据，我认为一部分数据已经到了服务器端。正常来讲，服务器端吧RDMA送来的这些数据处理掉，然后继续接收客户端发来的数据。但是这里的话服务器端出现了segmentation fault的问题，我认为是服务器的内存出现了泄露。我现在不知道应该怎么确定问题是出在我把数据送给grpc这里了还是说问题在我RDMA队列管理这里了。对于这个问题的定位您有什么好的建议吗？

目前的话，我试着把之前grpc中实现的RDMA通信完全剥离出来测试一下，看看我RDMA通信这个地方的实现有没有问题。这个代码我还在写，能运行之后我会放在github上，如您方便可否review一下，看一下我使用RDMA过程中有没有遗漏之处。

我最初的想法是使用RDMA的函数实现sendmsg和recvmsg方法，但是没想明白怎么把传递参数改成读写内存。但在RDMA使用过程中，ibv_post_send()和ibv_post_recv()，rdma_post_send()和rdma_post_recv()这种post方式我看过函数说明之后理解还不是很清楚，方便的话您可以解释一下这些函数干了什么吗？

如果方便的话，可否采用邮件或其他的联系方式？
谢谢：）

**Comment by Tuvie** [comment]
从这些描述很难定位到问题。听上去你的问题和brpc的实现没有关系。建议把你的代码放在github上，在这里给个链接。基于代码讨论才有基础。

**Comment by hellofinch** [comment]
我把我修改过的grpc的(代码)[https://github.com/hellofinch/rdma-grpc]传到了github上。
为了能够是grpc支持RDMA我主要添加了ib_和rdma_开头的问题在(这里)[https://github.com/hellofinch/rdma-grpc/tree/main/src/core/lib/iomgr]。
目前的问题是使用这个库的话能够进行简单的非流式通信，但是传输文件的话会有问题。使用的测试代码仓库在(这里)[https://github.com/hellofinch/grpc_comm/tree/master/grpc-fs]，一些log文件也在里边。

如果可以的话我们能否在(这里)[https://github.com/hellofinch/rdma-grpc/issues/1]继续讨论？把这个issue关闭，目前的问题可能和brpc相关性较低了。
